# 자바의 정석 연습문제 Ch8-4

### 문제

다음과 같은 메서드가 있을 때 예외를 잘못 처리한 것은 모두 고르시오

```java
void method() throws InvalidNumberException, NotANumberException {}

class NumberException extends RuntimeException {}
class InvalidNumberException extends NumberException {}
class NotANumberException extends NumberException{}
```

a. try {method();} catch(Exception e) {}

b. try {method();} catch(NumberException e) {} catch(Exception e) {}

c. try {method();} catch(Exception e) {} catch(NumberException e) {}

d. try {method();} catch(InvalidNumberException e) { } catch(NotANumberException e) {}

e. try {method();} catch(NumberException e) {}

f. try {method();} catch(RuntimeException e) {}

### 나의 풀이

InvalidNumberException, NotANumberException는 NumberException를 상속 받고 있고 NumberException은 RuntimeException를 상속 받는다.

a,b,d,e,f→잘 처리함

c->Exception 예외는 모든 예외를 처리할 수 있는 최고조상이다. catch 블럭 맨 마지막에 두어야 에러가 발생하지 않는다.

### 배운점

상속 관계를 잘 파악해야 문제가 잘 풀린다는 것을 알았고 Exception 예외가 catch문 맨 마지막에 있어야 한다는 개념을 배웠다.